CC=mpicc
CFLAGS=-std=c++11
CFLAGS1=-O0

all:
	$(CC) $(CFLAGS) $(CFLAGS) -o send_receive_brod_A_brod_B send_receive_brod_A_brod_B.cpp
	$(CC) $(CFLAGS) $(CFLAGS) -o scatter_gather_brod_A_brod_B scatter_gather_brod_A_brod_B.cpp

clean:
	rm -rf send_receive_brod_A_brod_B scatter_gather_brod_A_brod_B
