#!/bin/bash
#SBATCH -J iterMM           # job name
#SBATCH -o iterMM_job_%j.o       # output and error file name (%j expands to jobID)
#SBATCH -n 1              # total number of mpi tasks requested
#SBATCH -p normal     # queue (partition) -- normal, development, etc.
#SBATCH -t 00:30:00        # run time (hh:mm:ss) - 0.5 hours
#SBATCH --mail-user=mranjan@cs.stonybrook.edu
#SBATCH --mail-type=begin  # email me when the job starts
#SBATCH --mail-type=end    # email me when the job finishes
ibrun ./a_kij_i $1 >> output_kij_i
