CXX=g++
CXXFLAGS=-std=c++11 -I boost_1_65_1/

all:
	$(CXX) $(CXXFLAGS) -o graph_generator graph_generator.cpp
	$(CXX) $(CXXFLAGS) -o fredman-tarjan fredman-tarjan.cpp

clean:
	rm -rf graph_generator
	rm -rf fredman_tarjan
