#!/bin/bash
#SBATCH -J MST_Binary_search_G1            # job name
#SBATCH -o MST_Binary_search_G1_%j.o       # output and error file name (%j expands to jobID)
#SBATCH -n 1              # total number of mpi tasks requested
#SBATCH -p normal     # queue (partition) -- normal, development, etc.
#SBATCH -t 00:30:00        # run time (hh:mm:ss) - 0.5 hours
#SBATCH --mail-user=rokkumar@cs.stonybrook.edu
#SBATCH --mail-type=begin  # email me when the job starts
#SBATCH --mail-type=end    # email me when the job finishes
export CILK_NWORKERS=68
ibrun ./mst_bs 68
