CC=mpicc
CFLAGS=-std=c++11

all:
	$(CC) $(CFLAGS) -o rot_A_rot_B rot_A_rot_B.cpp
	$(CC) $(CFLAGS) -o rot_A_brod_B rot_A_brod_B.cpp
	$(CC) $(CFLAGS) -o brod_A_brod_B brod_A_brod_B.cpp

clean:
	rm -rf rot_A_rot_B rot_A_brod_B brod_A_brod_B
